#! /usr/bin/env bash

#MY_GIT_REPO=git@github.com:apache/accumulo
MY_GIT_REPO=https://gitbox.apache.org/repos/asf/accumulo
MY_STAGING_REPO_BASE=https://repository.apache.org/content/repositories
MY_RC_PROJECT=orgapacheaccumulo

shopt -s globstar
shopt -s nullglob

# Usage: $0 <candidateNumber>
main() {
  local cnum; [[ -n "$1" ]] && cnum=$1
  while [[ -z "$cnum" ]]; do
    read -r -p 'Enter the staging repository number: ' cnum
  done
  local candidate=$MY_RC_PROJECT-$cnum

  local branch; [[ -n "$2" ]] && branch=$2
  while [[ -z "$branch" ]]; do
    read -r -p 'Enter the git branch for this release candidate: ' branch
  done

  local commit; [[ -n "$3" ]] && commit=$3
  while [[ -z "$commit" ]]; do
    read -r -p 'Enter the git commit for this release candidate: ' commit
  done

  # must in in slash or wget gets confused with --no-parent
  local url=$MY_STAGING_REPO_BASE/$candidate/
  local tmpdir; tmpdir=$(dirname "$0")/candidates/$candidate
  local testsDir; testsDir="$(pwd)/tests"

  (mkdir -p "$tmpdir"/download && cd "$tmpdir" && download "$url" && verify "$branch" "$commit" "$testsDir")
}

# colorize mvn output
mvn() {
  trap 'echo -n "\033[m"' SIGHUP SIGINT SIGTERM
  command mvn "$@" --fail-at-end 2>&1 | tee -a "$tmpdir"/maven-log.txt | awk '
    BEGIN { IGNORECASE=1 }
    /BUILD SUCCESS/ { print "\033[1;36m" $0 "\033[m" ; next }
    /^\[FATAL\]/    { print "\033[1;31m" $0 "\033[m" ; next }
    /^\[ERROR\]/    { print "\033[1;31m" $0 "\033[m" ; next }
    /^\[TRACE\]/    { print "\033[2;33m" $0 "\033[m" ; next }
    /^\[WARNING\]/  { print "\033[1;33m" $0 "\033[m" ; next }
    /^\[DEBUG\]/    { print "\033[2;34m" $0 "\033[m" ; next }
    /^\[INFO\]/     { print "\033[0;37m" $0 "\033[m" ; next }
    /^\[ALL\]/      { print "\033[1;37m" $0 "\033[m" ; next }
    { print }
  '
  return "${PIPESTATUS[0]}"
}

green() { echo -e '\e[0;32m'"$*"'\e[0m'; }
yellow() { echo -e '\e[0;33m'"$*"'\e[0m'; }
red() { echo -e '\e[0;31m'"$*"'\e[0m'; }

# Usage: echo $(outof <expected> <actual>)
outof() {
  [[ -z "$1" ]] || [[ -z "$2" ]] || [[ -n "$3" ]] && red BUG-IN-SCRIPT && return 1
  local color=green; [[ $1 -eq $2 ]] || color=red
  echo "$($color "$2")"/"$(yellow "$1")"
}

# Usage: printHashSummary sha1|md5 <expectedHashes>
printHashSummary() {
  local type=${1,,}
  local expected=$2
  local actual; actual=$(wc -l <"${type^^}"SUM)
  local verified; verified=$("${type}"sum -c "${type^^}"SUM 2>/dev/null| grep -c 'OK$')
  echo -n "Found $(outof "$expected" "$actual") $type hashes (ignoring GPG signatures). "
  echo "Verified $(outof "$actual" "$verified")."
}

# Usage: download <url>
download() {
  local url=$1
  if [[ ! -e .download-complete ]]; then
    echo "Downloading $(yellow "$url")..."
    if wget -erobots=off --no-verbose \
      --recursive --level inf --no-parent --no-host-directories \
      --reject 'index.html,index.html.tmp,maven-metadata.xml*,archetype-catalog.xml' \
      -P download \
      "$url"; then touch .download-complete
    else
      echo "Unable to download from $(red "$url")"
      exit 1
    fi
  fi
  echo "Download of $(yellow "$url") complete."
}

verifyHashes() {
  local filecount=$1
  local file type
  local files; readarray -t files < <(find download/ -type f \! -name '*.sha1' \! -name '*.md5' \! -name '*.asc' | sort)
  for type in md5 sha1; do
    rm -f ${type^^}SUM
    touch ${type^^}SUM
    for file in "${files[@]}"; do
      if [[ -r "$file.$type" ]]; then
        echo "$(cat "$file.$type") *$file">>"${type^^}"SUM
      else
        echo "Missing $(red "$(pwd)/$file.$type")"
      fi
    done
    printHashSummary $type "$filecount"
  done
}

verifyDetachedSignatures() {
  local file
  local sigs=$1
  local goodsigs; goodsigs=$(for file in download/**/*.asc; do
    gpg --verify "$file"
  done 2>&1 | sort | uniq -c | grep 'Good signature' | awk '{print $1}')
  [[ -n "$goodsigs" ]] || goodsigs=0
  echo "Verified $(outof "$sigs" "$goodsigs") detached GPG signatures."
}

verifyRPMSignatures() {
  local rpms; rpms=$(find download/ -name '*.rpm' | wc -l)
  local goodrpms=0
  local pubkey
  echo "Found $(yellow "$rpms") RPMs. Checking GPG signatures..."
  local file
  for file in download/**/*.rpm; do
    if rpm --checksig "$file" >/dev/null; then
      goodrpms=$((goodrpms+1))
    else
      pubkey=$(rpm --checksig "$file" | grep -o '#........')
      gpg --armor --export "${pubkey#?}" > gpg-pubkey-"${pubkey#?}"
      echo "Unable to verify download/**/$(red "$(basename "$file")"). Import GPG key with:"
      yellow sudo rpm --import "$(pwd)/gpg-pubkey-${pubkey#?}"
    fi
  done

  echo "Verified $(outof "$rpms" "$goodrpms") RPM signatures."
}

verifyJars() {
  local commit=$1
  local numSources; numSources=$(find download/ -name '*-sources.jar' | wc -l)
  local numJavadoc; numJavadoc=$(find download/ -name '*-javadoc.jar' | wc -l)
  local numRegular; numRegular=$(find download/ -name '*.jar' \! -name '*-sources.jar' \! -name '*-javadoc.jar' | wc -l)
  echo "Found $(green "$numRegular") jars."
  echo "Found $(outof "$numRegular" "$numSources") expected sources."
  echo "Found $(outof "$numRegular" "$numJavadoc") expected javadoc."
  local file type jars
  local numSealed=0
  local numGoodBuildNum=0
  local numBadBuildNum=0
  local numDirtyBuildNum=0
  local m=META-INF/MANIFEST.MF
  local key
  readarray -t jars < <(find download/ -name '*.jar' \! -name '*-sources.jar' \! -name '*-javadoc.jar')
  for file in "${jars[@]}"; do
    [[ -f "$(dirname "$file")/$(basename "$file" .jar)-sources.jar" ]] || echo -e "Missing -sources.jar for \e[0;31m$file\e[0m"
    [[ -f "$(dirname "$file")/$(basename "$file" .jar)-javadoc.jar" ]] || echo -e "Missing -javadoc.jar for \e[0;31m$file\e[0m"
    if jar tf "$file" | grep -E -v '^(org/|org/apache/|org/apache/accumulo/.*|META-INF/.*|web/.*)$'; then
      echo "$(red "$(basename "$file")") contains unexpected content."
    fi
    if rm -rf META-INF && jar xf "$file" $m && dos2unix $m &>/dev/null; then
      if grep -q '^Sealed: true$' $m; then
        numSealed=$((numSealed+1))
      else
        echo "$(red "$file") is not sealed."
      fi
      key=$(grep '^Implementation-Build: ' $m | cut -c 23-)
      if [[ $key == "$commit" ]]; then
        numGoodBuildNum=$((numGoodBuildNum+1))
      elif [[ $key == "${commit}-dirty" ]]; then
        numDirtyBuildNum=$((numDirtyBuildNum+1))
        echo "$(basename "$file") has $(yellow dirty) Implementation Build: $(yellow "$key") (probably maven-release-plugin)"
      else
        numBadBuildNum=$((numBadBuildNum+1))
        echo "$(basename "$file") has $(red wrong) Implementation Build: $(red "$key")"
      fi
    else
      echo "$(red "$(basename "$file")") is not sealed."
      echo "$(red "$(basename "$file")") does not specify a build number."
    fi
  done
  for file in download/**/*-sources.jar; do
    [[ -f "$(dirname "$file")/$(basename "$file" -sources.jar).jar" ]] || echo -e "Extra source jar: \e[0;31m$file\e[0m"
  done
  for file in download/**/*-javadoc.jar; do
    [[ -f "$(dirname "$file")/$(basename "$file" -javadoc.jar).jar" ]] || echo -e "Extra javadoc jar: \e[0;31m$file\e[0m"
  done
  rm -rf META-INF
  echo "Verified $(outof "$numRegular" "$numSealed") jars are sealed."
  echo "$(outof "$numRegular" "$numGoodBuildNum") jars match $(yellow "$commit")"
  echo "$(outof 0 "$numDirtyBuildNum") jars match $(yellow "$commit")-dirty"
  echo "$(outof 0 "$numBadBuildNum") jars do not match $(yellow "$commit")"
}

verifySourceTarball() {
  local branch=$1
  local commit=$2
  local numSrc; numSrc=$(find download/ -type f -name '*-src.tar.gz' | wc -l)
  echo "Found $(outof 1 "$numSrc") expected source tarballs."
  local tarball; tarball=$(find download/ -type f -name '*-src.tar.gz')
  shasum -a 512 --tag "$(pwd)/$tarball"
  echo "Extracting the source tarball..."
  rm -rf src && mkdir src && tar -C src -x -f "$tarball"
  echo "Cloning and checking out branch $(yellow "$branch")..."
  rm -rf git git-export && git clone --no-checkout --separate-git-dir=git "$MY_GIT_REPO" git-export && (cd git-export && (git checkout -b "$branch"-test refs/tags/"$branch" || git checkout -b "$branch"-test origin/"$branch")) && rm -f git-export/.git && find git-export -type f -name '.gitignore' -exec rm -f {} \;
  echo "Comparing the following git branch to the source tarball:"
  git --git-dir=git log --graph -n1 --color --decorate "$branch"-test | head -1
  local head; head=$(git --git-dir=git log --no-color -n1 | head -1 | cut -c 8-)
  if [[ $head == "$commit" ]]; then
    echo "$(green HEAD) matches $(yellow "$commit")"
  else
    echo "$(red HEAD:"$head") does $(red NOT) match $(yellow "$commit")"
  fi
  if diff -r --brief git-export/ src/*/; then
    echo "Verified download/**/$(yellow "$(basename "$tarball")") matches git branch $(yellow "$branch")."
  else
    echo "$(red "$tarball") does not match $(red "$branch")."
  fi
}

verifyBinaryTarball() {
  local branch=$1
  local numBin; numBin=$(find download/ -type f -name '*-bin.tar.gz' | wc -l)
  echo "Found $(outof 1 "$numBin") expected binary tarballs."
  local tarball; tarball=$(find download/ -type f -name '*-bin.tar.gz')
  shasum -a 512 --tag "$(pwd)/$tarball"
  echo "Extracting the binary tarball..."
  rm -rf bin && mkdir bin && tar -C bin -x -f "$tarball"
  local file
  local count=0
  local lib
  local jars
  readarray -t jars < <(find download/ -name '*.jar' \! -name '*-sources.jar' \! -name '*-javadoc.jar')
  for file in "${jars[@]}"; do
    if [[ $branch =~ ^1[.].*$ ]]; then
      lib=(bin/*/lib/"$(basename "${file%-*}")".jar) # strip off version
    else
      lib=(bin/*/lib/"$(basename "${file}")")
    fi
    if diff "$file" "${lib[0]}" >/dev/null; then
      count=$((count+1))
    elif [[ -e "${lib[0]}" ]]; then
      echo "$(red "$file") does not match $(red "${lib[0]}")"
    else
      red "$(basename "$file") doesn't exist in lib"
    fi
  done
  echo "Verified $(outof ${#jars[@]} $count) jars match the contents of the lib directory in the binary tarball."
}

verifyMvnBuild() {
  mvn --version
  local h s t
  for s in '-DskipTests' ''; do
    for h in 2 3; do
      t=''; [[ -n "$s" ]] && t='out'
      echo "Verifying src/* builds with$t tests on Hadoop $h ($(yellow mvn clean verify -Dtimeout.factor=2 -Dhadoop.profile="$h" "$s"))"
      (cd src/* && mvn clean verify -Dhadoop.profile="$h" $s | grep -E '(BUILD|ERROR|WARNING)')
    done
  done
}

verifyTests() {
  local branch=$1
  local testsDir=$2
  local regex=".*([0-9][.][0-9][.][0-9]).*"
  [[ $branch =~ $regex ]]
  local version="${BASH_REMATCH[1]}"
  for script in "$testsDir"/*; do
    [[ -f "$script" ]] && [[ -x "$script" ]] && "$script" "$version"
  done
}

verify() {
  local branch=$1
  local commit=$2
  local testsDir=$3
  local filecount; filecount=$(find download/ -type f \! -name '*.sha1' \! -name '*.md5' | wc -l)
  local sigs; sigs=$(find download/ -type f -name '*.asc' | wc -l)
  local regular=$((filecount-sigs))
  local color=green; [[ "$regular" -eq "$sigs" ]] || color=red
  echo "Found $($color "$filecount") files: $($color "$regular") artifacts, $($color "$sigs") detached GPG signatures."
  verifyHashes "$regular"
  verifyDetachedSignatures "$sigs"
  #verifyRPMSignatures
  verifyJars "$commit"
  verifyBinaryTarball "$branch"
  verifySourceTarball "$branch" "$commit"
  #verifyMvnBuild                    # should be tested in jenkins
  #verifyTests "$branch" "$testsDir" # not working currently
}

umask 0022
main "$@"
#Debugging global variables
#env | egrep -v '^[A-Z_]*=' | sort
